

phases:
  Setup: True

  New Year: False
  Production: True
  Government: True
  Spring: True
  Summer: True
  Blockade: False
  Fall: True
  Winter: True

  Land Combat: True
  Naval Combat: True

  Scoring: False

first_year: 1936
last_year: 1945

victory: # conditions
  economic: 25

USA_public_opinion: [1941, 1942, 1943, 1944]
USA_forces: # add detailed troop list to allow customizing US forces
  1942: 1
  1943: 2
  1944: 3

year_order:
  - New Year
  - Production
  - Government
  - Spring
  - Summer
  - Blockade
  - Fall
  - Winter

turn_order_options:
  1: [Axis, USSR, West]
  2: [Axis, West, USSR]
  3: [West, Axis, USSR]
  4: [West, USSR, Axis]
  5: [USSR, West, Axis]
  6: [USSR, Axis, West]

peace_dividends:
  0: 16
  1: 12
  2: 4